/* eslint-disable no-undef */
export const downloadListCourses = [
  {
    id: 1,
    title: 'React Native',
    author: 'Duy Le',
    level: 'Advance',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/react-js-getting-started-v2.png'),
  },
  {
    id: 2,
    title: 'Android',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/software-development.jpg'),
  },
  {
    id: 3,
    title: 'iOS',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/ios-collection-views-getting-started-v1.png'),
  },
  {
    id: 4,
    title: 'React Native',
    author: 'Duy Le',
    level: 'Advance',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/react-js-getting-started-v2.png'),
  },
  {
    id: 5,
    title: 'Android',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/software-development.jpg'),
  },
  {
    id: 6,
    title: 'iOS',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/ios-collection-views-getting-started-v1.png'),
  },
  {
    id: 7,
    title: 'iOS',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/ios-collection-views-getting-started-v1.png'),
  },
  {
    id: 8,
    title: 'iOS',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/ios-collection-views-getting-started-v1.png'),
  },
]

export const searchListCourses = [
  {
    id: 1,
    title: 'React Native',
    author: 'Duy Le',
    level: 'Advance',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/react-js-getting-started-v2.png'),
  },
  {
    id: 2,
    title: 'Android',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/software-development.jpg'),
  },
  {
    id: 3,
    title: 'iOS',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/ios-collection-views-getting-started-v1.png'),
  },
]

export const sectionCourses = [
  {
    id: 1,
    title: 'React Native',
    author: 'Duy Le',
    level: 'Advance',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/react-js-getting-started-v2.png'),
  },
  {
    id: 2,
    title: 'Android',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/software-development.jpg'),
  },
  {
    id: 3,
    title: 'iOS',
    author: 'Thao Luu',
    level: 'Beginner',
    released: 'May 6, 2020',
    duration: '30h',
    reviews: 123,
    image: require('assets/images/ios-collection-views-getting-started-v1.png'),
  },
];

export const sectionPaths = [
  {
    id: 1,
    title: 'React Native',
    coursesAmount: '12 courses',
    image: require('assets/images/react.png'),
  },
  {
    id: 2,
    title: 'Android',
    coursesAmount: '12 courses',
    image: require('assets/images/android.png'),
  },
  {
    id: 3,
    title: 'iOS',
    coursesAmount: '12 courses',
    image: require('assets/images/ios.png'),
  },
];

export const searchListPaths = [
  {
    id: 1,
    title: 'React Native',
    coursesAmount: '12 courses',
    image: require('assets/images/react.png'),
  },
  {
    id: 2,
    title: 'Android',
    coursesAmount: '12 courses',
    image: require('assets/images/android.png'),
  },
  {
    id: 3,
    title: 'iOS',
    coursesAmount: '12 courses',
    image: require('assets/images/ios.png'),
  },
]

export const authors = [
  {
    id: 1,
    name: 'Cody House',
    coursesAmount: '12 courses',
    image: require('assets/images/cory-house.jpg'),
  },
  {
    id: 2,
    name: 'Don Robins',
    coursesAmount: '12 courses',
    image: require('assets/images/don-robins.jpeg'),
  },
  {
    id: 3,
    name: 'Scott Allen',
    coursesAmount: '12 courses',
    image: require('assets/images/scott-allen.jpg'),
  },
]